# Generated by Django 5.0.6 on 2024-06-24 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='aurhor',
            new_name='author',
        ),
    ]
